### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by BLAST1718** [VpsOP/ApexMiner#12]
Make this into a minion plugin?

**Comment by VpsOP** [comment]
Isn't it already a plugin?

**Comment by BLAST1718** [comment]
I mean like add more miners or maybe add farmers too

**Comment by VpsOP** [comment]
Not really thinking about adding this atm. Maybe i can make a separate plugin for farmer minions in the future

**Comment by thinh2118** [comment]
make just owner can break block.
